# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 Reid Crowe, N0RC
"""End-to-end tests of the real native boundary against a mock FTDI library (#37).

The mock (tests/native/mock_ft4222.c) is compiled per run. These tests skip
when no C compiler is available, unless N1MM_REQUIRE_NATIVE=1 (set in CI),
in which case a missing compiler fails the run.
"""

from __future__ import annotations

import os
import socket
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

import mock_ftdi as nb
import pytest

from n1mm_scope_bridge.cli import main
from n1mm_scope_bridge.emulator import Faults, Ft710Emulator
from n1mm_scope_bridge.radios.ft710 import FT710
from n1mm_scope_bridge.transport import ft4222 as ft
from n1mm_scope_bridge.transport.ft4222 import DeviceNotFound, Ft4222Reader, load_api

pytestmark = pytest.mark.native


@pytest.fixture(scope="session")
def mock_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    try:
        built = nb.build(tmp_path_factory.mktemp("mock-ftdi"))
    except nb.BuildUnavailable as err:
        if os.environ.get("N1MM_REQUIRE_NATIVE") == "1":
            pytest.fail(f"native tests required but {err}")
        pytest.skip(str(err))
    return built


def raw_stream(frames: int = 6, start_offset: int = 0) -> bytes:
    """What the radio's FT4222 would deliver, generated by the emulator."""
    emu = Ft710Emulator(faults=Faults(start_offset=start_offset))
    _, handle = emu.open_ex("FT4222 A")
    return b"".join(emu.spi_read(handle, 4096)[1] for _ in range(frames))


@pytest.fixture
def capture(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    path = tmp_path / "stream.bin"
    path.write_bytes(raw_stream(start_offset=1234))
    monkeypatch.setenv("N1MM_MOCK_FT4222_CAPTURE", str(path))
    monkeypatch.setenv("N1MM_MOCK_FT4222_LOG", str(tmp_path / "calls.log"))
    return path


def test_reader_streams_through_native_library(mock_dir: Path, capture: Path) -> None:
    reader = Ft4222Reader(load_api(str(mock_dir)))
    parsed = []
    for raw in reader:
        parsed.append(FT710.parse(raw))
        if len(parsed) == 5:
            reader.stop()
    assert all(p.status.vfo_hz == 14_074_000 for p in parsed)
    assert reader.resyncs >= 1  # the capture starts mid-frame
    calls = (capture.parent / "calls.log").read_text(encoding="utf-8").splitlines()
    assert calls[:5] == [
        "FT_OpenEx FT4222 A 2",
        "FT_SetTimeouts",
        "FT_SetLatencyTimer",
        "FT4222_SPIMaster_Init",
        "FT4222_SetClock",
    ]
    assert calls[-2:] == ["FT4222_UnInitialize", "FT_Close"]


def test_wrong_description_is_not_found(mock_dir: Path, capture: Path) -> None:
    with pytest.raises(DeviceNotFound, match="FT_DEVICE_NOT_FOUND"):
        Ft4222Reader(load_api(str(mock_dir)), description="FT4222 B").open()


def test_missing_device_without_capture(mock_dir: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("N1MM_MOCK_FT4222_CAPTURE", raising=False)
    with pytest.raises(DeviceNotFound):
        Ft4222Reader(load_api(str(mock_dir))).open()


def test_mock_rejects_wrong_spi_parameters(mock_dir: Path, capture: Path) -> None:
    api = load_api(str(mock_dir))
    status, handle = api.open_ex("FT4222 A")
    assert status == ft.FT_OK
    results = [
        api.spi_read(handle, 16)[0],  # before setup: FT_DEVICE_NOT_OPENED
        api._spi_init(handle, 2, ft.CLK_DIV_64, ft.CLK_IDLE_HIGH, ft.CLK_LEADING, 1),
        api.set_timeouts(handle, 50, 100),
        api.set_latency_timer(handle, 16),
        api.uninitialize(handle),
        api.close(handle),
        api.close(handle),  # stale handle is rejected, never read after free
    ]
    assert results == [3, 6, 6, 6, ft.FT_OK, ft.FT_OK, 1]


def test_cli_probe_and_run_through_native_library(
    mock_dir: Path, capture: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(["probe", "--ftdi-lib-dir", str(mock_dir)]) == 0
    assert "FT-710 found on 'FT4222 A'" in capsys.readouterr().out
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as rx:
        rx.bind(("127.0.0.1", 0))
        rx.settimeout(5)
        port = str(rx.getsockname()[1])
        argv = [
            "run",
            "--ftdi-lib-dir",
            str(mock_dir),
            "--duration",
            "0.6",
            "--rate",
            "10",
            "--port",
            port,
        ]
        assert main(argv) == 0
        root = ET.fromstring(rx.recvfrom(65535)[0])
    assert root.findtext("DataCount") == "850"
    capsys.readouterr()


def test_build_commands_per_platform(tmp_path: Path) -> None:
    win = nb.commands(
        tmp_path, platform="win32", is_64bit=True, which=lambda c: "x" if c == "cl" else None
    )
    assert [c[0] for c in win] == ["cl", "cl"]
    assert any("LibFT4222-64.dll" in part for part in win[1])
    gcc = nb.commands(
        tmp_path, platform="win32", is_64bit=False, which=lambda c: "x" if c == "gcc" else None
    )
    assert gcc[1][-2].endswith("LibFT4222.dll")
    linux = nb.commands(
        tmp_path, platform="linux", which=lambda c: "/usr/bin/cc" if c == "cc" else None
    )
    assert linux[0][-2].endswith("libft4222.so")
    with pytest.raises(nb.BuildUnavailable):
        nb.commands(tmp_path, platform="win32", which=lambda c: None)
    with pytest.raises(nb.BuildUnavailable):
        nb.commands(tmp_path, platform="darwin", which=lambda c: None)


def test_build_reports_compiler_failure(tmp_path: Path) -> None:
    def failing(cmd: object) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess([], 1, "", "boom")

    with pytest.raises(RuntimeError, match="boom"):
        nb.build(tmp_path, runner=failing, platform="linux", which=lambda c: "cc")
